name: Voicy MP3 Downloader

on:
  schedule:
    - cron: '0 * * * *'  # 毎時0分に実行
  workflow_dispatch:  # 手動実行用

# 明示的に権限を設定
permissions:
  contents: write
  actions: write

jobs:
  voicy-mp3-download:
    runs-on: ubuntu-latest
    
    steps:
      - name: チェックアウト
        uses: actions/checkout@v3
      
      - name: Python 3.10 セットアップ
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Chrome ブラウザのセットアップ
        uses: browser-actions/setup-chrome@v1
      
      - name: FFmpegのインストール
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          ffmpeg -version
      
      - name: 依存関係のインストール
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 selenium webdriver-manager
      
      - name: Voicy MP3ダウンロードの実行
        run: |
          # 出力ディレクトリの作成
          mkdir -p mp3_downloads
          mkdir -p temp_segments
          mkdir -p debug_files
          
          # ダウンロード履歴ファイルの確認
          if [ ! -f download_history.json ]; then
            echo "[]" > download_history.json
          fi
          
          # スクリプトの実行
          python voicy_mp3_downloader.py
          
          # ダウンロードしたファイルの確認
          echo "ダウンロードしたMP3ファイル一覧:"
          ls -la mp3_downloads/
      
      - name: 変更をコミットしてプッシュ
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          git add mp3_downloads/
          git add download_history.json
          
          # 変更があるかチェック
          if git diff --staged --quiet; then
            echo "変更はありません。コミットをスキップします。"
          else
            git commit -m "自動ダウンロード: $(date '+%Y-%m-%d %H:%M:%S')"
            git push
          fi
