name: Scrape Voicy Channel

on:
  schedule:
    # 毎日午前1時（UTC）に実行
    - cron: '0 1 * * *'
  workflow_dispatch:  # 手動実行も可能

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - name: リポジトリをチェックアウト
      uses: actions/checkout@v3
      
    - name: Python 3.9をセットアップ
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: 依存関係をインストール
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4
        
    - name: スクレイパーを実行
      run: python scrape_voicy.py
      
    - name: 変更があればコミットしてプッシュ
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add voicy_broadcasts.xml
        git diff --quiet && git diff --staged --quiet || (git commit -m "Voicy放送データを更新" && git push)
