name: Scrape Voicy Channel

on:
  schedule:
    # Run every day at 1:00 AM UTC
    - cron: '0 1 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4
        
    - name: Check file structure
      run: |
        ls -la
        pwd
        
    - name: Run scraper
      run: |
        # リポジトリルートディレクトリにスクリプトがあることを確認
        python ./scrape_voicy.py
      
    - name: Commit and push if changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add voicy_broadcasts.xml
        # コミットする前にファイルの存在を確認
        if [ -f voicy_broadcasts.xml ]; then
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update Voicy broadcast data" && git push)
        else
          echo "Warning: voicy_broadcasts.xml not found"
          exit 1
        fi
