name: Voicy MP3 Downloader

on:
  schedule:
    - cron: '0 0 * * *'  # 毎日午前0時に実行
  workflow_dispatch:  # 手動実行も可能

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: チェックアウト
        uses: actions/checkout@v4
          
      - name: Pythonセットアップ
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          
      - name: 依存関係のインストール
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          pip install requests beautifulsoup4 selenium webdriver-manager
          
      - name: ChromeDriverのインストール
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          
      - name: ディレクトリ作成
        run: |
          mkdir -p mp3_downloads
          mkdir -p temp_segments
          mkdir -p debug_files
          mkdir -p output
          
      - name: URLリストの作成
        run: |
          echo '["https://voicy.jp/channel/1234/567890", "https://voicy.jp/channel/1234/567891"]' > output/voicy_urls_only.json
          
      - name: MP3ダウンロード実行
        run: python downloader.py
        
      - name: 成果物のアップロード
        uses: actions/upload-artifact@v4
        with:
          name: downloaded-mp3s
          path: mp3_downloads/
          retention-days: 7
